# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title:               Code As Manuscript
tagline:             'Change the way you see your code.'
description:         'Writing your code and analyses as if <i>it</i> was the manuscript.'
url:                 http://codeasmanuscript.org

author:
  name:           'Code As Manuscript'

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/codeasmanuscript

lesson-list: [Git, Intro, Plotting, Wrangling, Rmarkdown, Macros, ODS]
category-list: [R, Git, Macros, ODS, Lessons]
tag-list: [Lessons, Git, GitHub, Macros, ODS, Assignment, Slides, Cheatsheet]